/*
 * FrameConfig.java
 *
 * Created on 3 de Maio de 2006, 17:23
 */

package webfotos.gui;

/**
 * Esta classe cria um frame com aba.
 * Extende a classe JDialog.
 * Seu construtor envia valores para a classe pai e chama o o método initComponents(),
 * que foi gerado automaticamente pela IDE.
 * @author guilherme
 */
public class FrameConfig extends javax.swing.JDialog {
    
    /**
     * Construtor da classe.
     * Recebe valores e retransmite para a classe pai.
     * e chama o método initComponents() que monta a parte gráfica.
     * @param parent Frame para a classe {@link javax.swing.JDialog JDialog}
     * @param modal Flag para a classe JDialog.
     */
    public FrameConfig(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jtpTabConfigs = new javax.swing.JTabbedPane();
        painelGeral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        painelGeral.setLayout(new java.awt.BorderLayout());

        jtpTabConfigs.addTab("Geral", painelGeral);

        getContentPane().add(jtpTabConfigs, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Método principal.
     * Invoca a classe {@link java.lang.Runnable Runnable} e armazena o método run() para iniciar o frame.
     * @param args args do método main.
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameConfig(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jtpTabConfigs;
    private javax.swing.JPanel painelGeral;
    // End of variables declaration//GEN-END:variables
    
}
