/*
 * PainelA2.java
 *
 * Created on 23 de Janeiro de 2006, 11:32
 */

package webfotos.gui;

/**
 * Gera um painel estático com o logo da A2Comunicação apresentando também o nome do programa, versão e ano.
 * @author guilherme
 */
public class PainelA2 extends javax.swing.JPanel {
    
    /**
     * Construtor da classe.
     * O construtor apenas chama o método initComponents() que tem a função de gerar um painel com as imagens e dados do programa.
     */
    public PainelA2() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblVersao = new javax.swing.JLabel();
        lblCopyRight = new javax.swing.JLabel();
        lblFundoA2 = new javax.swing.JLabel();

        setLayout(null);

        lblVersao.setFont(new java.awt.Font("Arial", 1, 12));
        lblVersao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersao.setText("Vers\u00e3o 1.5");
        add(lblVersao);
        lblVersao.setBounds(120, 200, 160, 15);

        lblCopyRight.setFont(new java.awt.Font("Arial", 0, 12));
        lblCopyRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCopyRight.setText("\u00a9 2005 A2 Comunica\u00e7\u00e3o");
        add(lblCopyRight);
        lblCopyRight.setBounds(120, 220, 160, 15);

        lblFundoA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sobre.png")));
        add(lblFundoA2);
        lblFundoA2.setBounds(0, 0, 400, 240);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCopyRight;
    private javax.swing.JLabel lblFundoA2;
    private javax.swing.JLabel lblVersao;
    // End of variables declaration//GEN-END:variables
    
}
