/*
 * SplashScreenA2.java
 *
 * Created on 23 de Janeiro de 2006, 09:59
 */

package webfotos.gui;

/**
 * Gera um painel de load com o logo da A2Comunicação apresentando também o nome do programa, versão e ano.
 * Instancia um objeto privado dentro da própria classe.
 * @author guilherme
 */
public class SplashScreenA2 extends javax.swing.JWindow {
    
    private static SplashScreenA2 instancia = new SplashScreenA2();
    
    /** Creates new form BeanForm */
    private SplashScreenA2() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblVersao = new javax.swing.JLabel();
        lblCopyRight = new javax.swing.JLabel();
        progressBarExecucao = new javax.swing.JProgressBar();
        lblFundoA2 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setAlwaysOnTop(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblVersao.setFont(new java.awt.Font("Arial", 1, 12));
        lblVersao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersao.setText("Vers\u00e3o 1.5");
        getContentPane().add(lblVersao);
        lblVersao.setBounds(120, 200, 160, 15);

        lblCopyRight.setFont(new java.awt.Font("Arial", 0, 12));
        lblCopyRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCopyRight.setText("\u00a9 2005 A2 Comunica\u00e7\u00e3o");
        getContentPane().add(lblCopyRight);
        lblCopyRight.setBounds(120, 220, 160, 15);

        getContentPane().add(progressBarExecucao);
        progressBarExecucao.setBounds(110, 130, 180, 18);

        lblFundoA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sobre.png")));
        getContentPane().add(lblFundoA2);
        lblFundoA2.setBounds(0, 0, 400, 240);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-241)/2, 400, 241);
    }
    // </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.dispose();
    }//GEN-LAST:event_formMouseClicked
    
    /**
     * Retorna o objeto instanciado na própria classe.
     * @return Retorna a instancia da classe.
     */
    public static SplashScreenA2 getInstance() {
        return instancia;
    }
    
    /**
     * Método principal.
     * Invoca a classe {@link java.lang.Runnable Runnable}, para iniciar uma thread e cria um método run()
     * para mostrar o SplashScreenA2.
     * @param args args do método main.
     */
    public static void main (String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreenA2().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCopyRight;
    private javax.swing.JLabel lblFundoA2;
    private javax.swing.JLabel lblVersao;
    private javax.swing.JProgressBar progressBarExecucao;
    // End of variables declaration//GEN-END:variables
    
}
